/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/6Hlg1lkPyAy
es Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar";
import Image from "next/image";

export function AboutUs() {
  return (
    <div className="flex flex-col min-h-[100dvh]">
      <main className="flex-1">
        <section className="bg-background py-12 md:py-20 lg:py-28">
          <div className="container px-4 md:px-6">
            <div className="grid md:grid-cols-2 gap-8 items-center">
              <div className="space-y-4">
                <h1 className="text-3xl md:text-4xl lg:text-5xl font-bold">
                  Effortless Booking for Professional Services
                </h1>
                <p className="text-muted-foreground text-lg">
                  Gaurvice is the trusted platform for booking reliable and
                  vetted service providers in your local area. Find and book the
                  best professionals with just a few taps.
                </p>
                <div className="flex gap-2">
                  <Link href={"/search/Cleaning"}>
                    <Button>Book Now</Button>
                  </Link>
                  <Link href={"/service"}>
                    <Button variant="outline">Learn More</Button>
                  </Link>
                </div>
              </div>
              <div className="hidden md:block">
                <Image
                  src="https://images.unsplash.com/photo-1556745753-b2904692b3cd?q=80&w=1373&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
                  width={600}
                  height={400}
                  alt="Hero Image"
                  className="rounded-xl"
                  style={{ aspectRatio: "600/400", objectFit: "cover" }}
                />
              </div>
            </div>
          </div>
        </section>
        <section className="bg-muted py-12 md:py-20 lg:py-28">
          <div className="container px-4 md:px-6">
            <div className="grid md:grid-cols-2 gap-8 items-center">
              <div>
                <Image
                  src="https://images.unsplash.com/photo-1623050632591-13118534319e?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
                  width={600}
                  height={400}
                  alt="Booking Process"
                  className="rounded-xl"
                  style={{ aspectRatio: "600/400", objectFit: "cover" }}
                />
              </div>
              <div className="space-y-4">
                <h2 className="text-3xl md:text-4xl font-bold">
                  Seamless Booking Process
                </h2>
                <p className="text-muted-foreground text-lg">
                  Gaurvice makes booking professional services a breeze. Simply
                  search for the service you need, compare providers, and
                  securely book your appointment in just a few taps.
                </p>
                <ul className="space-y-2">
                  <li className="flex items-center gap-2">
                    <SearchIcon className="h-5 w-5 text-primary" />
                    <span>Search for services in your area</span>
                  </li>
                  <li className="flex items-center gap-2">
                    <CalendarCheckIcon className="h-5 w-5 text-primary" />
                    <span>Compare availability and book online</span>
                  </li>
                  <li className="flex items-center gap-2">
                    <CheckIcon className="h-5 w-5 text-primary" />
                    <span>Receive confirmation and reminders</span>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </section>
        <section className="bg-background py-12 md:py-20 lg:py-28">
          <div className="container px-4 md:px-6">
            <div className="grid md:grid-cols-2 gap-8 items-center">
              <div className="space-y-4">
                <h2 className="text-3xl md:text-4xl font-bold">
                  Trusted Services, Vetted Providers
                </h2>
                <p className="text-muted-foreground text-lg">
                  Gaurvice partners with the best local service providers to
                  ensure you receive high-quality, reliable service every time.
                  Browse our wide range of offerings and book with confidence.
                </p>
                <div className="grid grid-cols-2 gap-4">
                  <div className="flex items-center gap-2">
                    <WrenchIcon className="h-6 w-6 text-primary" />
                    <span className="font-medium">Home Repair</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <ScissorsIcon className="h-6 w-6 text-primary" />
                    <span className="font-medium">Beauty &amp; Wellness</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <TruckIcon className="h-6 w-6 text-primary" />
                    <span className="font-medium">Moving &amp; Logistics</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <BriefcaseIcon className="h-6 w-6 text-primary" />
                    <span className="font-medium">Professional Services</span>
                  </div>
                </div>
              </div>
              <div className="hidden md:block">
                <Image
                  src="https://images.unsplash.com/photo-1596936773232-68c5364b44a3?q=80&w=1374&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
                  width={600}
                  height={400}
                  alt="Services"
                  className="rounded-xl"
                  style={{ aspectRatio: "600/400", objectFit: "cover" }}
                />
              </div>
            </div>
          </div>
        </section>
        <section className="bg-muted py-12 md:py-20 lg:py-28">
          <div className="container px-4 md:px-6">
            <div className="space-y-8 text-center">
              <div className="space-y-4">
                <h2 className="text-3xl md:text-4xl font-bold">
                  What Our Customers Say
                </h2>
                <p className="text-muted-foreground text-lg">
                  Hear from real people who have used Gaurvice to book
                  professional services.
                </p>
              </div>
              <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
                <Card>
                  <CardContent className="space-y-4">
                    <div className="flex items-center gap-4">
                      <Avatar>
                        <AvatarImage src="/placeholder-user.jpg" alt="Avatar" />
                        <AvatarFallback>JD</AvatarFallback>
                      </Avatar>
                      <div>
                        <div className="font-medium">John Doe</div>
                        <div className="text-muted-foreground text-sm">
                          Homeowner
                        </div>
                      </div>
                    </div>
                    <div className="prose text-muted-foreground">
                      <p>
                        Gaurvice made booking a plumber for my leaky faucet\n
                        so easy. The platform connected me with a reliable\n
                        provider who arrived on time and fixed the issue\n
                        quickly. Highly recommend
                      </p>
                    </div>
                  </CardContent>
                </Card>
                <Card>
                  <CardContent className="space-y-4">
                    <div className="flex items-center gap-4">
                      <Avatar>
                        <AvatarImage src="/placeholder-user.jpg" alt="Avatar" />
                        <AvatarFallback>SM</AvatarFallback>
                      </Avatar>
                      <div>
                        <div className="font-medium">Sarah Miller</div>
                        <div className="text-muted-foreground text-sm">
                          Small Business Owner
                        </div>
                      </div>
                    </div>
                    <div className="prose text-muted-foreground">
                      <p>
                        As a busy small business owner, I don&apos;t have time to\n
                        search for and vet service providers. Gaurvice has\n
                        been a lifesaver, helping me find and book reliable\n
                        professionals for my office needs.
                      </p>
                    </div>
                  </CardContent>
                </Card>
                <Card>
                  <CardContent className="space-y-4">
                    <div className="flex items-center gap-4">
                      <Avatar>
                        <AvatarImage src="/placeholder-user.jpg" alt="Avatar" />
                        <AvatarFallback>LW</AvatarFallback>
                      </Avatar>
                      <div>
                        <div className="font-medium">Lisa Wang</div>
                        <div className="text-muted-foreground text-sm">
                          Busy Mom
                        </div>
                      </div>
                    </div>
                    <div className="prose text-muted-foreground">
                      <p>
                        As a busy mom, I don&apos;t have a lot of time to spare.\n
                        Gaurvice has been a lifesaver, helping me book\n
                        appointments for everything from house cleaning to\n
                        childcare with just a few taps. The platform is so\n
                        convenient and reliable.
                      </p>
                    </div>
                  </CardContent>
                </Card>
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}

function BriefcaseIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 20V4a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v16" />
      <rect width="20" height="14" x="2" y="6" rx="2" />
    </svg>
  );
}

function CalendarCheckIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M8 2v4" />
      <path d="M16 2v4" />
      <rect width="18" height="18" x="3" y="4" rx="2" />
      <path d="M3 10h18" />
      <path d="m9 16 2 2 4-4" />
    </svg>
  );
}

function CheckIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20 6 9 17l-5-5" />
    </svg>
  );
}

function GaugeIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m12 14 4-4" />
      <path d="M3.34 19a10 10 0 1 1 17.32 0" />
    </svg>
  );
}

function ScissorsIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="6" cy="6" r="3" />
      <path d="M8.12 8.12 12 12" />
      <path d="M20 4 8.12 15.88" />
      <circle cx="6" cy="18" r="3" />
      <path d="M14.8 14.8 20 20" />
    </svg>
  );
}

function SearchIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  );
}

function TruckIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M14 18V6a2 2 0 0 0-2-2H4a2 2 0 0 0-2 2v11a1 1 0 0 0 1 1h2" />
      <path d="M15 18H9" />
      <path d="M19 18h2a1 1 0 0 0 1-1v-3.65a1 1 0 0 0-.22-.624l-3.48-4.35A1 1 0 0 0 17.52 8H14" />
      <circle cx="17" cy="18" r="2" />
      <circle cx="7" cy="18" r="2" />
    </svg>
  );
}

function WrenchIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M14.7 6.3a1 1 0 0 0 0 1.4l1.6 1.6a1 1 0 0 0 1.4 0l3.77-3.77a6 6 0 0 1-7.94 7.94l-6.91 6.91a2.12 2.12 0 0 1-3-3l6.91-6.91a6 6 0 0 1 7.94-7.94l-3.76 3.76z" />
    </svg>
  );
}
